FROM ft-rails:on-build
EXPOSE 3000
CMD ["rails", "s", "-b", "0.0.0.0", "-p", "3000"]



# docker build --tag ft-rails:on-build ft_rails/
# git clone https://bitbucket.org/railstutorial/sample_app_4th_ed.git app
# docker build --tag ex02app .
# docker run -it --rm -p 3000:3000 ex02app